export const status = {
  CHECKED_IN: 'CHECKED_IN',
  ACCEPTED: 'ACCEPTED',
  SENDING: 'SENDING',
  CHECKED_OUT: 'CHECKED_OUT',
  IS_DUE: 'IS_DUE',
  RETURNING: 'RETURNING',
  RETURNED: 'RETURNED',
  DECLINED_BY_OWNER: 'DECLINED_BY_OWNER',
  CANCELED_BY_SENDER: 'CANCELED_BY_SENDER',
};

export const dueStatus = {
  DUE_TOMORROW: 'DUE_TOMORROW',
  DUE_SOON: 'DUE_SOON',
};
