export const status = {
  CHECKED_IN: 'CHECKED_IN',
  ACCEPTED: 'ACCEPTED',
  SENDING: 'SENDING',
  CHECKED_OUT: 'CHECKED_OUT',
  IS_DUE: 'IS_DUE',
  RETURNING: 'RETURNING',
  RETURNED: 'RETURNED',
  DECLINED: 'DECLINED',
};

export const dueStatus = {
  DUE_TOMORROW: 'DUE_TOMORROW',
  DUE_SOON: 'DUE_SOON',
};
